apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
  template:
    metadata: 
      labels:
        app: second-app
        tier: backend
    spec: 
      containers:
        - name: second-node
          image: sri1411/kub-first-app:2
          imagePullPolicy: Always
          livenessProbe: 
            httpGet: 
              path: /
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 5
        # - name: ...
        #   image: ...
